# -*- coding: utf-8 -*-
"""Assemble Royal Society Interface versions of main.tex and appendix.tex.

Body content is extracted VERBATIM from paper/els-cas-paper/{main,appendix}.tex.
Only journal-specific wrapping changes:
  - documentclass rsproca_new (single column: no multicols)
  - RSI front matter (\title/\author/\address/\subject/\keywords/\corres/abstract/fmtext)
  - RSI end matter (\ethics/\dataccess/\aucontribute/\competing/\funding/\ack)
  - biblatex (\addbibresource + \printbibliography) instead of natbib/bst
  - [pos=H] float spec -> [H]
  - unicode dashes normalised to TeX ASCII forms
"""
import io, re, sys

ELS = r"d:/AI_RESEARCH/ClusteringResearch/paper/els-cas-paper"
RSI = r"d:/AI_RESEARCH/ClusteringResearch/paper/Royal_Society_Interface_Paper"

def read(p):
    with io.open(p, "r", encoding="utf-8") as f:
        return f.read().splitlines()

def transform(text):
    # Flexible float placement instead of the CAS-source hard "[pos=H]":
    # with hard [H] a figure that does not fit the remaining page is pushed
    # wholesale to the next page and the class's \flushbottom stretches the
    # leftover space across the page (ugly mid-page gaps).
    text = text.replace("[pos=H]", "[!htbp]")
    text = text.replace("‑", "-")    # non-breaking hyphen
    text = text.replace("—", "---")  # em dash
    text = text.replace("–", "--")   # en dash
    # Typo fix (present in the els source): the "%" comment right after
    # "scale." eats the following space, rendering "scale.The composition".
    text = text.replace("scale.%, in a corpus", "scale. %, in a corpus")
    # Stale-caption fix (present in the els source): the Table 4
    # (tab:egt_vs_llm_summary) caption still describes an older transposed
    # layout with dedicated "Evidence" columns and EGT/LLM *rows*; the
    # current table has three columns (Pattern / EGT prediction / LLM
    # observation) with the evidence pointers embedded in the cells.
    text = text.replace(
        "``Evidence'' columns refer to figures and tables in this paper; "
        "numerical values for the EGT row come",
        "Figure and table pointers embedded in the cells refer to the "
        "evidence reported elsewhere in this paper; numerical values in the "
        "``EGT prediction'' column come",
    )
    text = text.replace(
        "those for the LLM row come",
        "those in the ``LLM observation'' column come",
    )
    # --- Figure B.14 fix (stale in the els source): the appendix text of the
    # confidence-threshold robustness check describes a PER-MODEL unfit-rate
    # figure with a tau=0.9 vertical line, but the included file
    # (ijcai_fig7_unfit_vs_threshold_small_llm.pdf) showed the LSTM-only
    # unfit rate by strategy-space size (3/4/5). The per-model figure the text
    # describes is regenerated by
    # analysis/appendix_figures/fig_unfit_vs_threshold_small_llm_by_model.py,
    # whose tau=0.9 values reproduce the hybrid pipeline's retained counts
    # exactly (Gemma-3 12B 1.2%, Qwen3 8B 10.8%, Llama-3.1 8B 33.9%).
    text = text.replace(
        "all_figures/ijcai_fig7_unfit_vs_threshold_small_llm.pdf",
        "all_figures/fig_unfit_vs_threshold_small_llm_by_model.pdf",
    )
    text = text.replace(
        "reports the unfit-trajectory rate as a function of the LSTM-output "
        "confidence threshold $\\tau$, computed separately",
        "reports the unfit-trajectory rate -- the fraction of trajectories "
        "left unclassified by the hybrid rule + LSTM pipeline -- as a "
        "function of the LSTM-output confidence threshold $\\tau$, computed "
        "separately",
    )
    text = text.replace(
        "the unfit rate stays below $30\\%$ for Gemma-3~12B and Qwen3~8B and "
        "below $50\\%$ for Llama-3.1~8B;",
        "the unfit rate is $1.2\\%$ for Gemma-3~12B, $10.8\\%$ for Qwen3~8B "
        "and $33.9\\%$ for Llama-3.1~8B;",
    )
    text = text.replace(
        "\\caption{Unfit (non-classifiable) trajectory rate as a function of "
        "the LSTM-output confidence threshold $\\tau$ for the three "
        "open-weight small LLMs. The vertical line at $\\tau{=}0.9$ marks the "
        "threshold used in the main analysis.",
        "\\caption{Unfit (non-classifiable) trajectory rate -- the fraction "
        "of agent trajectories left unclassified by the hybrid rule + LSTM "
        "pipeline -- as a function of the LSTM-output confidence threshold "
        "$\\tau$ for the three open-weight small LLMs. The dashed vertical "
        "line at $\\tau{=}0.9$ marks the threshold used in the main "
        "analysis, where the unfit rate is $1.2\\%$ for Gemma-3~12B, "
        "$10.8\\%$ for Qwen3~8B and $33.9\\%$ for Llama-3.1~8B.",
    )
    # --- Figure B.13 fix (stale in the els source): the caption and lead-in
    # text still describe the older three-regime version of the small-LLM
    # penalties grid, but fig_small_penalties_subplots.pdf shows all six
    # multipliers (lambda = 1000 down to 0.01, top to bottom).
    text = text.replace(
        "reports the per-cell mean penalties at the three stake regimes that "
        "match the proprietary analysis ($\\lambda \\in \\{0.1, 1, 10\\}$).",
        "reports the per-cell mean penalties across the full six-multiplier "
        "sweep of the open-weight corpus "
        "($\\lambda \\in \\{0.01, 0.1, 1, 10, 100, 1000\\}$); the middle "
        "rows ($\\lambda \\in \\{0.1, 1, 10\\}$, marked Low/Ord./High) match "
        "the three stake regimes of the proprietary analysis.",
    )
    text = text.replace(
        "Rows group three stake regimes (\\textbf{High}: $\\lambda{=}10$; "
        "\\textbf{Ordinary}: $\\lambda{=}1$; \\textbf{Very low}: "
        "$\\lambda{=}0.1$);",
        "Rows are the six stake multipliers of the open-weight sweep, from "
        "$\\lambda{=}1000$ (top) down to $\\lambda{=}0.01$ (bottom); the "
        "$\\lambda{=}10$ (\\textbf{High}), $\\lambda{=}1$ (\\textbf{Ord.}) "
        "and $\\lambda{=}0.1$ (\\textbf{Low}) rows match the three stake "
        "regimes of the proprietary analysis;",
    )
    # --- Heading B.5.4 fix (stale in the els source): the subsubsection was
    # titled "Strategy recognition via supervised machine learning" but its
    # entire content is the language-effect analysis of the baseline corpus.
    text = text.replace(
        "\\subsubsection{Strategy recognition via supervised machine "
        "learning}\\label{appendix:ml}",
        "\\subsubsection{The language effect: agent scores and strategy "
        "mix}\\label{appendix:ml}",
    )
    text = text.replace(
        "including a per-model supervised-learning breakdown "
        "(Appendix~\\ref{appendix:ml})",
        "including a complementary language-level analysis of agent scores "
        "and inferred strategies (Appendix~\\ref{appendix:ml})",
    )
    return text

# ----------------------------------------------------------------- main.tex
lines = read(ELS + "/main.tex")

# body: from \section{Introduction} up to and including the "In summary" paragraph
i_start = next(i for i, l in enumerate(lines) if l.startswith(r"\section{Introduction}"))
i_end   = next(i for i, l in enumerate(lines) if l.startswith("In summary, language and incentives"))
body = lines[i_start:i_end + 1]

# abstract: content between \begin{abstract} and \end{abstract}
a0 = next(i for i, l in enumerate(lines) if l.strip() == r"\begin{abstract}")
a1 = next(i for i, l in enumerate(lines) if l.strip() == r"\end{abstract}")
abstract = lines[a0 + 1:a1]

# NOTE: the template's optional \begin{fmtext} first-page block is NOT used:
# with this paper's long abstract the first-page text collides with the
# class's fixed-position licence notice. The Introduction therefore keeps its
# opening paragraph, exactly as in the els-cas source.

body_txt = transform("\n".join(body))
abstract_txt = transform("\n".join(abstract))

main_out = r"""%% Royal Society Interface submission
%% Converted from the Elsevier CAS manuscript in paper/els-cas-paper (2026-07-17).
%% Body content is ported VERBATIM from els-cas-paper/main.tex; only the
%% journal wrapping differs (class, front/end matter, biblatex bibliography).
%% Single-column layout: the template's optional \begin{multicols}{2} wrapper
%% is deliberately NOT used.

%% Local-toolchain workaround: this machine's MiKTeX pairs a 2026-06-01 LaTeX
%% kernel with a biblatex that fails to load under it. Rolling the kernel back
%% to 2025-06-01 restores compatibility. Remove once the local MiKTeX is fully
%% updated.
%% The guard is NOT cosmetic. On Overleaf (TeX Live 2025, format 2025-06-01)
%% the unconditional form patches nothing -- "Current format date selected, no
%% patches applied" -- yet still rolls INDIVIDUAL packages back to whatever
%% release best approximates the target: graphics and amsmath both land on
%% their 2019 versions. Loading it only on a format newer than the rollback
%% target confines the workaround to the machine that needs it.
\IfFormatAtLeastTF{2026-01-01}{\RequirePackage[2025-06-01]{latexrelease}}{}

\documentclass[openacc]{rsproca_new}

%% Packages required by the manuscript body (amsmath/amssymb/graphicx/xcolor,
%% hyperref and biblatex are already loaded by the class).
\usepackage{booktabs}
\usepackage{tabularx}
\usepackage{float}
\usepackage{placeins}
\usepackage{enumerate}

%% The supplementary appendix is compiled as a SEPARATE document
%% (appendix.tex -> appendix.pdf). Pull in its labels so that \ref{} to
%% appendix sections/figures/tables resolve to the right numbers.
%% Build order: pdflatex appendix -> pdflatex main -> biber main -> pdflatex main x2.
\usepackage{xr}
\externaldocument{appendix}

%% Bibliography database (style is fixed by the class: biblatex/biber, phys)
\addbibresource{mybib.bib}

%% Numeric subsection numbering (2.1, 3.2, ...) instead of the class default
%% "(a)", "(b)": cross-references such as "Section 3.2" would otherwise print
%% as an ambiguous "(b)", and the standalone supplementary appendix refers to
%% main-text subsections by their numeric form.
\renewcommand\thesubsection{\thesection.\arabic{subsection}}
\renewcommand\thesubsubsection{\thesubsection.\arabic{subsubsection}}

%% Do not stretch vertical glue to force a flush bottom margin: with many
%% large floats this produces big mid-page gaps. Leftover space (if any)
%% goes to the bottom of the page instead.
\raggedbottom

\jname{rsif}
\Journal{J R Soc Interface\ }

\begin{document}

%%%% Article title
\title{Payoff scaling shapes cooperation in LLM agents across languages}

%%%% Authors ($\dagger$: equal contribution, $\star$: corresponding authors)
\author{Trung-Kiet Huynh$^{1,3,\dagger}$, Dao-Sy Duy-Minh$^{1,3,\dagger}$, Thanh-Bang Cao$^{2,3}$, Phong-Hao Le$^{2,3}$, Hong-Dan Nguyen$^{2,3}$, Phu-Quy Nguyen-Lam$^{1,3}$, Minh-Luan Nguyen-Vo$^{2,3}$, Hong-Phat Pham$^{2,3}$, Phu-Hoa Pham$^{1,3}$, Thien-Kim Than$^{2,3}$, Chi-Nguyen Tran$^{2,3}$, Huy Tran$^{2,3}$, Gia-Thoai Tran-Le$^{2,3}$, Alessio Buscemi$^{4}$, Le Hong Trang$^{2,3,\star}$ and The Anh Han$^{5,\star}$}

%%%% Author addresses
\address{$^{1}$Faculty of Information Technology, University of Science (HCMUS), Ho Chi Minh City, Vietnam\\
$^{2}$Faculty of Computer Science and Engineering, Ho Chi Minh City University of Technology (HCMUT), Ho Chi Minh City, Vietnam\\
$^{3}$Vietnam National University -- Ho Chi Minh City (VNU-HCM), Ho Chi Minh City, Vietnam\\
$^{4}$Luxembourg Institute of Science and Technology (LIST), Luxembourg\\
$^{5}$School of Computing, Engineering and Digital Technologies, Teesside University, Middlesbrough, United Kingdom\\[4pt]
$^{\dagger}$These authors contributed equally to this work.}

%%%% Subject entries
\subject{artificial intelligence, game theory, multi-agent systems}

%%%% Keyword entries
\keywords{emergence of cooperation, large language models, evolutionary game theory, iterated Prisoner's Dilemma, cross-lingual behaviour, intention recognition}

%%%% Corresponding authors
\corres{Le Hong Trang\\
\email{lhtrang@hcmut.edu.vn}\\[2pt]
The Anh Han\\
\email{t.han@tees.ac.uk}}

%%%% Abstract
\begin{abstract}
__ABSTRACT__
\end{abstract}

%% (No \begin{fmtext} first-page block: the long abstract leaves no room on
%% the first page -- the body text would collide with the licence notice.)

\maketitle

__BODY__

%%%%%%%%%% End matter (Royal Society statements) %%%%%%%%%%

\ethics{This work did not involve human participants, animal subjects or fieldwork; all experiments are computational simulations of interactions between large language model agents.}

%% TODO(authors): insert the repository/DOI before submission.
\dataccess{The gameplay logs, prompt templates, trained classifiers and analysis code supporting this article will be made publicly available upon acceptance.}

%% TODO(authors): complete the CRediT-style contribution statement.
\aucontribute{T.-K.H. and D.-S.D.-M. contributed equally to this work and are joint first authors. All authors contributed to the research and the writing of the manuscript, and gave final approval for publication.}

\competing{The authors declare that they have no known competing financial interests or personal relationships that could have appeared to influence the work reported in this paper.}

\funding{T.A.H. is supported by EPSRC (grant EP/Y00857X/1).}

\ack{T.A.H. acknowledges travel support from the HCMUT-VNUHCM (Adjunct Professorship scheme HCMUT-VNUHCM).}

%%%%%%%%%% Bibliography %%%%%%%%%%

\printbibliography

\end{document}
"""
main_out = (main_out
            .replace("__ABSTRACT__", abstract_txt)
            .replace("__BODY__", body_txt))

with io.open(RSI + "/main.tex", "w", encoding="utf-8", newline="\n") as f:
    f.write(main_out)

# ------------------------------------------------------------- appendix.tex
alines = read(ELS + "/appendix.tex")
a_start = next(i for i, l in enumerate(alines) if l.startswith(r"\section{Supplement to Methodology}"))
a_end   = next(i for i, l in enumerate(alines) if l.strip() == r"\FloatBarrier" and i > a_start)
abody = transform("\n".join(alines[a_start:a_end + 1]))

app_out = r"""%% Royal Society Interface submission -- Supplementary Appendix (ESM)
%% Converted from paper/els-cas-paper/appendix.tex (2026-07-17); body content
%% is ported VERBATIM. Compiles STANDALONE (references to main-text
%% section/figure/table numbers are hard-coded, exactly as in the source).

%% Local-toolchain workaround (see main.tex): roll the kernel back so the
%% installed biblatex loads. Guarded so it stays a no-op on Overleaf/TeX Live,
%% where the unconditional form rolls graphics and amsmath back to 2019.
\IfFormatAtLeastTF{2026-01-01}{\RequirePackage[2025-06-01]{latexrelease}}{}

\documentclass[openacc]{rsproca_new}

%% Packages required by the appendix body (amsmath/amssymb/graphicx,
%% hyperref and biblatex are already loaded by the class).
\usepackage{booktabs}
\usepackage{multirow}
\usepackage{float}
\usepackage{placeins}
\usepackage{chngcntr}   % section-based float numbering (Figure A.1, Table B.1, ...)

%% Bibliography database (style is fixed by the class: biblatex/biber, phys)
\addbibresource{mybib.bib}

%% Numeric subsection numbering (A.1, B.1.1, ...) instead of the class default
%% "(a)"/"i": matches how the main text refers to appendix sections.
\renewcommand\thesubsection{\thesection.\arabic{subsection}}
\renewcommand\thesubsubsection{\thesubsection.\arabic{subsubsection}}

%% See main.tex: avoid \flushbottom stretching around large floats.
\raggedbottom

\jname{rsif}
\Journal{J R Soc Interface\ }

\begin{document}

\begin{center}
  {\LARGE\bfseries Supplementary Appendix}\\[6pt]
  {\large\itshape Payoff scaling shapes cooperation in LLM agents across languages}
\end{center}
\vspace{1.5em}

\appendix

% Number figures/tables as A.1, A.2, B.1, ... (reset per appendix section) so
% that references from the main paper (e.g. "Figure B.1") cannot be confused
% with the main text's own Figure/Table numbers.
\counterwithin{figure}{section}
\counterwithin{table}{section}

__BODY__

% --- Appendix-local reference list (only works cited in this appendix). ---
\printbibliography

\end{document}
"""
app_out = app_out.replace("__BODY__", abody)

with io.open(RSI + "/appendix.tex", "w", encoding="utf-8", newline="\n") as f:
    f.write(app_out)

print("main.tex body lines:", len(body))
print("appendix.tex body lines:", a_end + 1 - a_start)
print("body starts:", body[0][:60])
print("body ends:", body[-1][:60])
