"""The payoff scale is already in the opening move, before anything is known.

A rescaling could act through the course of play, by changing how a model reads
the history its opponent has produced, or it could act on the reading of the
matrix itself.  Round one separates the two.  At round one an agent has seen
the matrix, the language of the prompt and one line of persona, and nothing
else; no move has been made and no history exists.  Whatever of the scale
effect is visible there cannot have been generated by the dynamics of play.

Panel a draws opening-move cooperation against the payoff scale, one small
panel per model, with the other four models behind in grey so that a curve is
read against its neighbours without five curves crossing in one frame.  The
effect is plainly there: Grok 4.20 opens with cooperation in 7 per cent of its
games at the smallest scale and 76 per cent at the largest, and GPT-5.4 Nano
moves from 35 to 65 per cent.  Qwen3 235B-A22B is the exception and barely
moves, which is the same model that barely moves in the mixture figure.

Panel b asks whether the opening move is merely a copy of how much a model
cooperates overall.  Across the fifty model-by-scale cells the two agree well,
which is unsurprising, but the agreement is carried by the differences between
models.  Within a model the two can come apart entirely, and in Claude Haiku
4.5 and Qwen3 235B-A22B they move in opposite directions, so the opening move
is its own quantity and not a restatement of the cooperation rate.

Panel c looks at the other instruction that acts before any play, the persona
line, on the same opening move.  Plotted is the gap between an agent told to be
cooperative and one told to be selfish.  Two things are visible.  The gap is
negative in every model, that is, the agent told to cooperate opens with
cooperation less often, which is the inversion the persona section of the
manuscript reports; and the payoff scale moves that gap, sharply in Claude
Haiku 4.5 and Gemini 3.5 Flash-Lite, so the scale is acting on the instruction
as well as on the matrix, and it is doing so before the first move.

The sub-unit regime is the two scales at which every payoff printed is at most
1.  Intervals are 95 per cent percentile bootstrap intervals over agent-games.
This figure does not separate an effect on the prior from a further effect on
how history is later weighed; it shows only that most of the effect is present
before any history exists.
"""
from __future__ import annotations

import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
import style as S      # noqa: E402
import data as D       # noqa: E402

SUB_MAX = 0.1          # the two scales at which every payoff printed is <= 1
LO, HI = 0.01, 1000.0


def curve(g, model):
    s = (g[g.model == model].groupby("scale_nominal").first_move_coop
         .mean().reindex(S.SCALES))
    return s.to_numpy()


def ci(g, model, scale):
    x = g[(g.model == model) & (g.scale_nominal == scale)].first_move_coop
    return D.bootstrap_ci(x)


def main():
    g = D.games()
    g = g[g.model.isin(S.MODEL_ORDER)].copy()
    g["sub"] = g.scale_nominal <= SUB_MAX
    lam = np.array(S.SCALES, dtype=float)
    curves = {m: curve(g, m) for m in S.MODEL_ORDER}

    cells = (g.groupby(["model", "scale_nominal"], observed=True)
             .agg(fm=("first_move_coop", "mean"),
                  cr=("coop_rate", "mean")).reset_index())
    r_all = float(np.corrcoef(cells.fm, cells.cr)[0, 1])
    t08 = D.table("T08_first_move.csv").set_index("model")

    print("  opening-move cooperation at the extreme scales")
    for m in S.MODEL_ORDER:
        a, b = ci(g, m, LO), ci(g, m, HI)
        lo = curves[m][0]
        hi = curves[m][-1]
        rw = float(np.corrcoef(cells[cells.model == m].fm,
                               cells[cells.model == m].cr)[0, 1])
        print(f"    {S.MODEL_SHORT[m]:11s} "
              f"lam=0.01 {lo:.3f} [{a[0]:.3f}, {a[1]:.3f}]   "
              f"lam=1000 {hi:.3f} [{b[0]:.3f}, {b[1]:.3f}]   "
              f"range {t08.loc[m].range_round1:.3f} against "
              f"{t08.loc[m].range_later:.3f} later "
              f"(x{t08.loc[m].ratio:.2f})   within-model r={rw:+.2f}")
    print(f"  opening move against overall cooperation, 50 cells: r = {r_all:.3f}")
    print("  persona gap on the opening move, told cooperative minus told selfish")
    gaps = {}
    for m in S.MODEL_ORDER:
        row = []
        for sub in (True, False):
            x = g[(g.model == m) & (g["sub"] == sub)]
            c = x[x.personality == "cooperative"].first_move_coop
            s = x[x.personality == "selfish"].first_move_coop
            row.append(c.mean() - s.mean())
        gaps[m] = row
        print(f"    {S.MODEL_SHORT[m]:11s} sub-unit {row[0]:+.3f}   "
              f"supra-unit {row[1]:+.3f}")

    fig = plt.figure(figsize=(S.FULL, 4.0))
    gs = fig.add_gridspec(2, 6, height_ratios=[1.0, 1.45], hspace=0.68,
                          wspace=0.35, left=0.065, right=0.985,
                          top=0.92, bottom=0.10)
    # 5 top panels span columns across the width: 5 subplots in top row
    gs_top = gs[0, :].subgridspec(1, 5, wspace=0.25)
    tops = [fig.add_subplot(gs_top[0, i]) for i in range(5)]
    # Two square panels in bottom row: centered nicely
    axB = fig.add_subplot(gs[1, 0:3])
    axC = fig.add_subplot(gs[1, 3:6])
    axB.set_box_aspect(1)
    axC.set_box_aspect(1)

    # --- a: one small panel per model, the others behind in grey -----------
    for i, (ax, m) in enumerate(zip(tops, S.MODEL_ORDER)):
        for other in S.MODEL_ORDER:
            if other == m:
                continue
            ax.plot(lam, curves[other], color=S.HAIRLINE, lw=0.8, zorder=2)
        los, his = zip(*(ci(g, m, s) for s in S.SCALES))
        ax.fill_between(lam, los, his, color=S.MODEL_C[m], alpha=0.18, lw=0,
                        zorder=3)
        ax.plot(lam, curves[m], color=S.MODEL_C[m], lw=1.3, zorder=4)
        ax.plot(lam, curves[m], color=S.MODEL_C[m], marker=S.MODEL_M[m],
                lw=0, ms=2.8, markerfacecolor=S.SURFACE, markeredgewidth=0.8,
                zorder=5)
        S.scale_axis(ax, band=True, label=None, ticks=False)
        ax.set_xticks([0.01, 1, 1000])
        ax.set_xticklabels(["0.01", "1", "1000"])
        ax.set_ylim(0, 1)
        S.strip(ax)
        if i == 0:
            ax.set_yticks([0, 0.5, 1.0])
            ax.set_yticklabels(["0", "50", "100%"])
            ax.set_ylabel("opens with C")
        else:
            ax.set_yticks([])
            ax.spines["left"].set_visible(False)
        ax.set_xlabel(S.MODEL_SHORT[m], color=S.MODEL_C[m], fontsize=S.FS_NOTE,
                      fontweight="bold", labelpad=3.0)
        ax.text(0.98, 0.03, f"range {t08.loc[m].range_round1:.2f}",
                transform=ax.transAxes, ha="right", va="bottom",
                fontsize=5.9, color=S.MODEL_C[m])

    S.panel(tops[0], "a", "the scale is there on move 1")
    tops[2].text(0.5, -0.36, r"payoff scale $\lambda$", transform=tops[2].transAxes,
                 ha="center", va="top", fontsize=S.FS_NOTE, color=S.MUTED)

    # --- b: the opening move is not the overall rate -----------------------
    axB.plot([0, 1], [0, 1], color=S.HAIRLINE, lw=0.8, zorder=1)
    axB.text(0.955, 0.985, "equal", fontsize=5.9, color=S.MUTED,
             ha="right", va="top", rotation=39, rotation_mode="anchor")
    for m in S.MODEL_ORDER:
        sel = cells.model == m
        axB.scatter(cells.cr[sel], cells.fm[sel], s=13, color=S.MODEL_C[m],
                    marker=S.MODEL_M[m], linewidths=0, alpha=0.85, zorder=3)
    for m, x, y, ha in (
        ("Claude-Haiku-4.5", 0.02, 0.31, "left"),
        ("Qwen3-235B-A22B", 0.02, 0.62, "left"),
        ("Gemini-3.5-Flash-Lite", 0.36, 0.92, "left"),
        ("GPT-5.4-Nano", 0.86, 0.44, "right"),
        ("Grok-4.20-Non-Reasoning", 0.98, 0.18, "right"),
    ):
        sel = cells.model == m
        rw = float(np.corrcoef(cells.fm[sel], cells.cr[sel])[0, 1])
        axB.text(x, y, f"{S.MODEL_SHORT[m]}  r={rw:+.2f}", fontsize=5.9,
                 color=S.MODEL_C[m], ha=ha, va="center", zorder=6)
    S.strip(axB, grid_axis="both")
    axB.set_xlim(0, 1.0)
    axB.set_ylim(0, 1.0)
    axB.set_xticks([0, 0.25, 0.5, 0.75, 1.0])
    axB.set_xticklabels(["0", "25", "50", "75", "100%"])
    axB.set_yticks([0, 0.5, 1.0])
    axB.set_yticklabels(["0", "50", "100%"])
    axB.set_xlabel("cooperation over all ten rounds")
    axB.set_ylabel("opens with C")
    S.panel(axB, "b", f"across cells r = {r_all:.2f}, within a model not")

    # --- c: the persona instruction, on the opening move --------------------
    ys = np.arange(len(S.MODEL_ORDER))[::-1]
    for y, m in zip(ys, S.MODEL_ORDER):
        sub, sup = gaps[m]
        axC.plot([sub, sup], [y, y], color=S.MODEL_C[m], lw=1.0, zorder=2)
        S.dot(axC, sub, y, color=S.MODEL_C[m], marker=S.MODEL_M[m], size=22,
              filled=False)
        S.dot(axC, sup, y, color=S.MODEL_C[m], marker=S.MODEL_M[m], size=22)
    S.zero_rule(axC, 0.0, vertical=True, lw=0.9)
    axC.text(0.035, len(S.MODEL_ORDER) - 0.55,
             "the instruction\nas written", fontsize=5.9, color=S.MUTED,
             ha="left", va="center", linespacing=1.15)
    top_m = S.MODEL_ORDER[0]
    for j, name in ((0, "sub-unit"), (1, "supra-unit")):
        axC.annotate(name, xy=(gaps[top_m][j], len(S.MODEL_ORDER) - 1),
                     xytext=(0, 9), textcoords="offset points", fontsize=5.9,
                     color=S.MODEL_C[top_m], ha="center", va="bottom")
    axC.set_yticks(ys)
    axC.set_yticklabels([S.MODEL_SHORT[m] for m in S.MODEL_ORDER])
    for lab, m in zip(axC.get_yticklabels(), S.MODEL_ORDER):
        lab.set_color(S.MODEL_C[m])
    S.strip(axC, grid_axis="x")
    axC.tick_params(axis="y", length=0)
    axC.set_xlim(-1.1, 0.42)
    axC.set_xticks([-1.0, -0.5, 0.0])
    axC.set_ylim(-0.8, len(S.MODEL_ORDER) - 0.05)
    axC.set_xlabel("told cooperative minus told selfish")
    S.panel(axC, "c", "told cooperative opens C less")

    S.caption(fig,
             "20,000 opening moves, 400 per model and payoff scale; bands and "
             "intervals are 95% percentile bootstraps over agent-games;\n"
             "shading on a and the open markers on c are the sub-unit regime, "
             "the two scales at which every payoff printed is at most 1", y=-0.005)

    S.save(fig, "f_firstmove")


if __name__ == "__main__":
    main()
